"""add scrim_time column

Revision ID: 075a5d4b421a
Revises: 32821c9a21a5
Create Date: 2025-07-27 09:44:41.693846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075a5d4b421a'
down_revision: Union[str, Sequence[str], None] = '32821c9a21a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrim', sa.Column('scrim_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrim', 'scrim_time')
    # ### end Alembic commands ###
