"""update session table

Revision ID: 17c9006eb3d5
Revises: 91b6ed4b2e1d
Create Date: 2025-08-31 20:08:06.467772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c9006eb3d5'
down_revision: Union[str, Sequence[str], None] = '91b6ed4b2e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('session', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('session', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('session', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'user_agent')
    op.drop_column('session', 'ip_address')
    op.drop_column('session', 'updated_at')
    op.drop_column('session', 'expires_at')
    # ### end Alembic commands ###
