"""create initial tables

Revision ID: 27f345fb4e4a
Revises: 420350b049d1
Create Date: 2025-08-08 19:32:09.082397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27f345fb4e4a'
down_revision: Union[str, Sequence[str], None] = '420350b049d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_role_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('registration_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('logs_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_created_at'), 'tournament', ['created_at'], unique=False)
    op.create_index(op.f('ix_tournament_guild_id'), 'tournament', ['guild_id'], unique=False)
    op.create_index(op.f('ix_tournament_name'), 'tournament', ['name'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('captain_id', sa.BigInteger(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret')
    )
    op.create_index(op.f('ix_team_captain_id'), 'team', ['captain_id'], unique=False)
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_member_id'), 'team_member', ['id'], unique=False)
    op.create_index(op.f('ix_team_member_user_id'), 'team_member', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_member_user_id'), table_name='team_member')
    op.drop_index(op.f('ix_team_member_id'), table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_index(op.f('ix_team_captain_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_tournament_name'), table_name='tournament')
    op.drop_index(op.f('ix_tournament_guild_id'), table_name='tournament')
    op.drop_index(op.f('ix_tournament_created_at'), table_name='tournament')
    op.drop_table('tournament')
    op.drop_table('task')
    op.drop_table('guild_config')
    # ### end Alembic commands ###
