"""rename scrim_channel to scrim, add more columns

Revision ID: 32821c9a21a5
Revises: f87044fba84a
Create Date: 2025-07-27 09:06:09.278934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32821c9a21a5"
down_revision: Union[str, Sequence[str], None] = "f87044fba84a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scrim",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("admin_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("participant_role_id", sa.BigInteger(), nullable=True),
        sa.Column("organizer_role_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("scrims_channel")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scrims_channel",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("guild_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("scrims_channel_pkey")),
    )
    op.drop_table("scrim")
    # ### end Alembic commands ###
