"""add registration_open flag

Revision ID: 37995e78fe2c
Revises: 13f33b7a50e5
Create Date: 2025-08-01 17:37:00.463649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37995e78fe2c'
down_revision: Union[str, Sequence[str], None] = '13f33b7a50e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrim', sa.Column('registration_open', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrim', 'registration_open')
    # ### end Alembic commands ###
