"""remove current_size col

Revision ID: 452e5f2a42ba
Revises: b178b2513c03
Create Date: 2025-07-30 17:09:07.153972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452e5f2a42ba'
down_revision: Union[str, Sequence[str], None] = 'b178b2513c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'current_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('current_size', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
