"""add registration opening and closing time

Revision ID: 732c3780d76a
Revises: dfbfc47692cb
Create Date: 2025-07-31 15:14:47.070796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732c3780d76a'
down_revision: Union[str, Sequence[str], None] = 'dfbfc47692cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrim', sa.Column('registration_opening_time', sa.DateTime(), nullable=False))
    op.add_column('scrim', sa.Column('registration_closing_time', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'team', ['secret'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_column('scrim', 'registration_closing_time')
    op.drop_column('scrim', 'registration_opening_time')
    # ### end Alembic commands ###
