"""update session table

Revision ID: 91b6ed4b2e1d
Revises: 059acadf4b21
Create Date: 2025-08-31 10:32:40.295618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b6ed4b2e1d'
down_revision: Union[str, Sequence[str], None] = '059acadf4b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('session', 'refresh_token_expires_at')
    op.drop_column('session', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('session', sa.Column('refresh_token_expires_at', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('session', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
