"""add secret column

Revision ID: 9c28ce6d395b
Revises: f00fe15b036b
Create Date: 2025-07-30 16:32:00.112304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c28ce6d395b'
down_revision: Union[str, Sequence[str], None] = 'f00fe15b036b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('secret', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'secret')
    # ### end Alembic commands ###
