"""create initial tables

Revision ID: ad38a820fa5b
Revises: c992413a12a3
Create Date: 2025-08-31 22:25:22.291058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad38a820fa5b'
down_revision: Union[str, Sequence[str], None] = 'c992413a12a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrim', sa.Column('organizer_role_id', sa.BigInteger(), nullable=True))
    op.add_column('scrim', sa.Column('participant_role_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrim', 'participant_role_id')
    op.drop_column('scrim', 'organizer_role_id')
    # ### end Alembic commands ###
