"""add team_member table

Revision ID: b178b2513c03
Revises: 9c28ce6d395b
Create Date: 2025-07-30 16:55:58.997062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b178b2513c03'
down_revision: Union[str, Sequence[str], None] = '9c28ce6d395b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_member_id'), 'team_member', ['id'], unique=False)
    op.create_index(op.f('ix_team_member_user_id'), 'team_member', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_member_user_id'), table_name='team_member')
    op.drop_index(op.f('ix_team_member_id'), table_name='team_member')
    op.drop_table('team_member')
    # ### end Alembic commands ###
