"""create initial tables

Revision ID: bceb537bdd96
Revises: 27f345fb4e4a
Create Date: 2025-08-09 20:05:23.409499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bceb537bdd96'
down_revision: Union[str, Sequence[str], None] = '27f345fb4e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('team_tournament_id_fkey'), 'team', type_='foreignkey')
    op.drop_column('team', 'tournament_id')
    op.drop_column('team', 'max_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('max_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('team', sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('team_tournament_id_fkey'), 'team', 'tournament', ['tournament_id'], ['id'])
    # ### end Alembic commands ###
