"""add scrim_id in team_member

Revision ID: dfbfc47692cb
Revises: 452e5f2a42ba
Create Date: 2025-07-30 17:15:00.392329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbfc47692cb'
down_revision: Union[str, Sequence[str], None] = '452e5f2a42ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_member', sa.Column('scrim_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team_member', 'scrim', ['scrim_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.drop_column('team_member', 'scrim_id')
    # ### end Alembic commands ###
