"""create initial tables

Revision ID: f00fe15b036b
Revises: 
Create Date: 2025-07-29 16:13:57.085978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00fe15b036b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('participant_role_id', sa.BigInteger(), nullable=True),
    sa.Column('organizer_role_id', sa.BigInteger(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('teamcap', sa.Integer(), nullable=False),
    sa.Column('max_team_size', sa.Integer(), nullable=False),
    sa.Column('best_of', sa.Integer(), nullable=False),
    sa.Column('tournament_type', sa.Integer(), nullable=False),
    sa.Column('bracket_type', sa.Integer(), nullable=False),
    sa.Column('prize', sa.String(), nullable=True),
    sa.Column('rules', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logs_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('register_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('announcements_channel_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrim_guild_id'), 'scrim', ['guild_id'], unique=False)
    op.create_index(op.f('ix_scrim_name'), 'scrim', ['name'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('captain_id', sa.BigInteger(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('current_size', sa.Integer(), nullable=False),
    sa.Column('scrim_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scrim_id'], ['scrim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_captain_id'), 'team', ['captain_id'], unique=False)
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_index(op.f('ix_team_captain_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_scrim_name'), table_name='scrim')
    op.drop_index(op.f('ix_scrim_guild_id'), table_name='scrim')
    op.drop_table('scrim')
    # ### end Alembic commands ###
